s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(40,"&"))
print(s.count("o"))
print(s.endswith("es2"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T"))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print("python programming".istitle())
print("python programming".title())
print("Hello".replace("l","w"))

